// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: xerror.proto

package xerror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一业务错误载体
type BizError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 自定义业务错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 对外展示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BizError) Reset() {
	*x = BizError{}
	mi := &file_xerror_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizError) ProtoMessage() {}

func (x *BizError) ProtoReflect() protoreflect.Message {
	mi := &file_xerror_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizError.ProtoReflect.Descriptor instead.
func (*BizError) Descriptor() ([]byte, []int) {
	return file_xerror_proto_rawDescGZIP(), []int{0}
}

func (x *BizError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BizError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_xerror_proto protoreflect.FileDescriptor

const file_xerror_proto_rawDesc = "" +
	"\n" +
	"\fxerror.proto\x12\x06xerror\"8\n" +
	"\bBizError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\vZ\t./;xerrorb\x06proto3"

var (
	file_xerror_proto_rawDescOnce sync.Once
	file_xerror_proto_rawDescData []byte
)

func file_xerror_proto_rawDescGZIP() []byte {
	file_xerror_proto_rawDescOnce.Do(func() {
		file_xerror_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xerror_proto_rawDesc), len(file_xerror_proto_rawDesc)))
	})
	return file_xerror_proto_rawDescData
}

var file_xerror_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xerror_proto_goTypes = []any{
	(*BizError)(nil), // 0: xerror.BizError
}
var file_xerror_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xerror_proto_init() }
func file_xerror_proto_init() {
	if File_xerror_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xerror_proto_rawDesc), len(file_xerror_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xerror_proto_goTypes,
		DependencyIndexes: file_xerror_proto_depIdxs,
		MessageInfos:      file_xerror_proto_msgTypes,
	}.Build()
	File_xerror_proto = out.File
	file_xerror_proto_goTypes = nil
	file_xerror_proto_depIdxs = nil
}
